Presentation/myTechnicCase.Web/Models/ErrorViewModel.cs
namespace myTechnicCase.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Presentation/myTechnicCase.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myTechnicCase.Application.Interfaces.Services;
using myTechnicCase.Web.Models;

namespace myTechnicCase.Web.Controllers;

public class HomeController : Controller
{
    private readonly IPersonnelService _personnelService;
    private readonly ITeamService _teamService;
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger, IPersonnelService personnelService, ITeamService teamService)
    {
        _teamService = teamService;
        _personnelService = personnelService;
        _logger = logger;
    }

    public IActionResult Index()
    {
        var activePersonnels = _personnelService.GetAllPersonnels().Count;
        ViewBag.activePerson = activePersonnels.ToString();
        var activeTeam = _teamService.GetAllTeams().Count;
        ViewBag.activeTeam = activeTeam.ToString();
        var waitPersonnels = _personnelService.GetAllPersonnels().Where(x=>x.TeamName == null).Count();
        ViewBag.waitPersonnels = waitPersonnels.ToString();

        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Presentation/myTechnicCase.Web/Controllers/PersonnelController.cs
using Microsoft.AspNetCore.Mvc;
using myTechnicCase.Application.Dtos.Personnel;
using myTechnicCase.Application.Interfaces.Services;

namespace myTechnicCase.Web.Controllers;

public class PersonnelController : Controller
{
    private readonly IPersonnelService _personnelService;

    public PersonnelController(IPersonnelService personnelService)
    {
        _personnelService = personnelService;
    }
    // GET
    public IActionResult Index()
    {
        List<PersonnelListDto> personnels = _personnelService.GetAllPersonnels().ToList();
        return View(personnels);
    }
    [HttpGet]
    public IActionResult Create()
    {
        var personnelDto = new PersonelCreateDto();
        return View(personnelDto);
    }

    [HttpPost]
    public ActionResult Create(PersonelCreateDto personnelDto)
    {
        if (ModelState.IsValid)
            _personnelService.AddPersonnel(personnelDto);

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Delete(int id)
    {
        if (ModelState.IsValid)
        {
            _personnelService.DeleteById(id);
            return RedirectToAction(nameof(Index));
        }
        return NotFound();
    }
    
    [HttpGet]
    public IActionResult Update(int? id)
    {
        if (id is null)
            return RedirectToAction(nameof(Index));
        var data = _personnelService.GetAllPersonnels().Find(x => x.Id == id);
        return View(data);
    }

    [HttpPost]
    public IActionResult Update(PersonnelListDto dto)
    {
        bool isUpdated = _personnelService.Update(dto);
        return RedirectToAction("Index");
    }

}

Presentation/myTechnicCase.Web/Controllers/ShiftController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using myTechnicCase.Application.Dtos.Shift;
using myTechnicCase.Application.Interfaces.Services;

namespace myTechnicCase.Web.Controllers;

public class ShiftController : Controller
{
    private readonly IShiftService _shiftService;
    private readonly ITeamService _teamService;
    public ShiftController(IShiftService shiftService, ITeamService teamService)
    {
        _shiftService = shiftService;
        _teamService = teamService;
    }
    // GET
    public IActionResult Index()
    {
        List<ShiftListDto> shiftList = _shiftService.GetAllShifts().ToList();
        return View(shiftList);
    }

    private void FillDropdownItems(ShiftCreateDto dto)
    {
        dto.Teams = _teamService.GetAllTeams().Select(e => new SelectListItem { Value = e.Id.ToString(), Text = $"{e.Name}" }).ToList();
    }
    [HttpGet]
    public IActionResult Create()
    {
        var shiftDto = new ShiftCreateDto();
        FillDropdownItems(shiftDto);
        return View(shiftDto);
    }

    [HttpPost]
    public ActionResult Create(ShiftCreateDto shiftCreateDto)
    {
        if (ModelState.IsValid)
            _shiftService.AddShift(shiftCreateDto);

        return RedirectToAction(nameof(Index));
    }

    public IActionResult Delete(int id)
    {
        if (ModelState.IsValid)
        {
            _shiftService.DeleteById(id);
            return RedirectToAction(nameof(Index));
        }
        return NotFound();
    }
    
    [HttpGet]
    public IActionResult Update(int? id)
    {
        if (id is null)
            return RedirectToAction(nameof(Index));
        var data = _shiftService.GetAllShifts().Find(x => x.Id == id);
        return View(data);
    }

    [HttpPost]
    public IActionResult Update(ShiftListDto dto)
    {
        bool isUpdated = _shiftService.Update(dto);
        return RedirectToAction("Index");
    }
}

Presentation/myTechnicCase.Web/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using myTechnicCase.Application.Dtos.Team;
using myTechnicCase.Application.Interfaces.Services;

namespace myTechnicCase.Web.Controllers;

public class TeamController : Controller
{
	private readonly ITeamService _teamService;
	private readonly IPersonnelService _personnelService;
	private readonly IShiftService _shiftService;

	public TeamController(ITeamService teamService, IPersonnelService personnelService)
	{
		_teamService = teamService;
		_personnelService = personnelService;
	}
	// GET
	public IActionResult Index()
	{
		var teams = _teamService.GetAllTeams();


		return View(teams);
	}
	[HttpGet]
	public IActionResult Create()
	{
		var team = new TeamCreateDto();
		FillDropdownItems(team);
		return View(team);
	}

	[HttpPost]
	public ActionResult Create(TeamCreateDto teamDto)
	{
		if (ModelState.IsValid)
			_teamService.CreateTeam(teamDto);
		return RedirectToAction(nameof(Index));
	}
	public void FillDropdownItems(TeamCreateDto dto)
	{
		dto.Personnels = _personnelService.GetPersonnelsThatHasNoTeams().Select(e => new SelectListItem { Value = e.Id.ToString(), Text = $"{e.Name} {e.Surname}" })
			.ToList();
	}
	public IActionResult Delete(int id)
	{
		if (ModelState.IsValid)
		{
			_teamService.DeleteById(id);

			return RedirectToAction(nameof(Index));
		}
		return NotFound();
	}

	[HttpGet]
	public IActionResult Update(int? id)
	{
		if (id is null)
			return RedirectToAction(nameof(Index));
		var data = _teamService.GetAllTeams().Find(x=>x.Id == id);
		return View(data);
	}

	[HttpPost]
	public IActionResult Update(TeamListDto dto)
	{
		bool isUpdated = _teamService.Update(dto);
		return RedirectToAction("Index");
	}
}

Presentation/myTechnicCase.Web/Views/Personnel/Create.cshtml
@model myTechnicCase.Application.Dtos.Personnel.PersonelCreateDto
<div class="row">
<div class="col-xxl-12">
    <!--begin::Tables Widget 9-->
    <div class="card card-xxl-stretch mb-5 mb-xl-8">
        <!--begin::Header-->
        <div class="card-header border-0 pt-5">
            <h3 class="card-title align-items-start flex-column">
                <span class="card-label fw-bolder fs-3 mb-1">Team Create</span>
            </h3>
        </div>
        <!--end::Header-->
        <!--begin::Body-->
        <div class="card-body">
            <form asp-action="Create">
                <div class="row">
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="PersonnelCode" class="col-form-label"></label>
                            <input asp-for="PersonnelCode" class="form-control"/>
                            <span asp-validation-for="PersonnelCode" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="Name" class="col-form-label"></label>
                            <input asp-for="Name" class="form-control"/>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="Surname" class="col-form-label"></label>
                            <input asp-for="Surname" class="form-control"/>
                            <span asp-validation-for="Surname" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="UserName" class="col-form-label"></label>
                            <input asp-for="UserName" class="form-control"/>
                            <span asp-validation-for="UserName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="Email" class="col-form-label"></label>
                            <input asp-for="Email" class="form-control"/>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="Phone" class="col-form-label"></label>
                            <input asp-for="Phone" class="form-control"/>
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="Address" class="col-form-label"></label>
                            <input asp-for="Address" class="form-control"/>
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row-cols-4">
                            <label asp-for="Title" class="col-form-label"></label>
                            <input asp-for="Title" class="form-control"/>
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="mb-10 form-check"></div>
                <div class="row">
                    <div class="col">
                        <a class="btn btn-secondary mr-2" asp-action="Index"><i class="fa fa-arrow-left"></i> Back To List</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <div class="col">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>

Presentation/myTechnicCase.Web/Views/Personnel/Index.cshtml
@model IEnumerable<myTechnicCase.Application.Dtos.Personnel.PersonnelListDto>
@{
	ViewData["Title"] = "Personnel List";
}
<div class="row">
	<div class="col-xxl-12">
		<div class="card card-xxl-stretch mb-5 mb-xl-8">
			<div class="card-header border-0 pt-5">
				<h3 class="card-title align-items-start flex-column">
					<span class="card-label fw-bolder fs-3 mb-1">Personnel List</span>
				</h3>
				<div class="card-toolbar" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-trigger="hover" title="">
					<a asp-action="Create" class="btn btn-success float-end ml-5">
						<i class="fa fa-plus"></i>	Create Personnel
					</a>
				</div>
			</div>
			<div class="card-body py-3">
				<table class="table table-striped table-row-bordered gy-5 gs-7 dt-init">
					<thead>
						<tr class="fw-bolder fs-6 text-gray-700">
							<th></th>
							<th>
								@Html.DisplayNameFor(model => model.PersonnelCode)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.Name)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.Surname)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.UserName)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.Email)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.Phone)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.Address)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.Title)
							</th>
							<th>
								@Html.DisplayNameFor(model => model.TeamName)
							</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
						{
							<tr>
								<td>
									<a asp-action="Update" asp-route-id="@item.Id" data-toggle="tooltip" title="Update"><i class="fas fa-pencil-alt text-success" style="font-size:1.5rem"></i> </a>
									<a asp-action="Delete" asp-route-id="@item.Id" data-toggle="tooltip" title="Delete"><i class="far fa-trash-alt text-danger ml-2" style="font-size:1.5rem"></i> </a>
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.PersonnelCode)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Name)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Surname)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.UserName)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Email)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Phone)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Address)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.Title)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.TeamName)
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

@section Scripts{
	<script>
		$('document').ready(function () {
			InitDatatables();
		})
	</script>
}

Presentation/myTechnicCase.Web/Views/Personnel/Update.cshtml
@model myTechnicCase.Application.Dtos.Personnel.PersonnelListDto

@{
    ViewData["Title"] = "Personnel Edit";
}
<div class="row">
    <div class="col-xxl-12">
        <!--begin::Tables Widget 9-->
        <div class="card card-xxl-stretch mb-5 mb-xl-8">
            <!--begin::Header-->
            <div class="card-header border-0 pt-5">
                <h3 class="card-title align-items-start flex-column">
                    <span class="card-label fw-bolder fs-3 mb-1">Personnel Edit</span>
                </h3>
            </div>
            <!--end::Header-->
            <!--begin::Body-->
            <div class="card-body">
                <!--begin::Table container-->
                <form asp-action="Update" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="PersonnelCode" class="col-form-label"></label>
                                <input asp-for="PersonnelCode" class="form-control"/>
                                <span asp-validation-for="PersonnelCode" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="Name" class="col-form-label"></label>
                                <input asp-for="Name" class="form-control"/>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="Surname" class="col-form-label"></label>
                                <input asp-for="Surname" class="form-control"/>
                                <span asp-validation-for="Surname" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="UserName" class="col-form-label"></label>
                                <input asp-for="UserName" class="form-control"/>
                                <span asp-validation-for="UserName" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="Email" class="col-form-label"></label>
                                <input asp-for="Email" class="form-control"/>
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="Phone" class="col-form-label"></label>
                                <input asp-for="Phone" class="form-control"/>
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="Address" class="col-form-label"></label>
                                <input asp-for="Address" class="form-control"/>
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row-cols-4">
                                <label asp-for="Title" class="col-form-label"></label>
                                <input asp-for="Title" class="form-control"/>
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="mb-10 form-check">
                    </div>
                    <a class="btn btn-secondary mr-2" asp-action="Index"><i class="fa fa-arrow-left"></i> Back To Personnel List</a>  
                    <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save Changes</button>
                </form>
                <!--end::Table container-->
            </div>
            <!--begin::Body-->
        </div>
        <!--end::Tables Widget 9-->
    </div>
</div>

Presentation/myTechnicCase.Web/Views/Shared/_Footer.cshtml
<div class="container-fluid d-flex flex-column flex-md-row align-items-center justify-content-between">
	<div class="text-dark order-2 order-md-1">
		<span class="text-muted fw-bold me-1">2023©</span>
		<a href="http://www.mytechnic.aero" target="_blank" class="text-gray-800 text-hover-primary">myTECHNIC</a>
	</div>
	<ul class="menu menu-gray-600 menu-hover-primary fw-bold order-1">
		<li class="menu-item">
			<a href="#" target="_blank" class="menu-link px-2">Created Erhan ÖZĞAN</a>
		</li>
	</ul>
</div>

Presentation/myTechnicCase.Web/Views/Shared/_Header.cshtml
<div class="container-fluid d-flex align-items-stretch justify-content-between">
	<!--begin::Aside mobile toggle-->
	<!--end::Aside mobile toggle-->
	<!--begin::Mobile logo-->
	<div class="d-flex align-items-center flex-grow-1 flex-lg-grow-0">
		<a href="../../demo6/dist/index.html" class="d-lg-none">
		</a>
	</div>
	<!--end::Mobile logo-->
	<!--begin::Wrapper-->
	<div class="d-flex align-items-stretch justify-content-between flex-lg-grow-1">
		<!--begin::Navbar-->
		<div class="d-flex align-items-stretch" id="kt_header_nav">
			<!--begin::Menu wrapper-->
			<div class="header-menu align-items-stretch" data-kt-drawer="true" data-kt-drawer-name="header-menu" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="end" data-kt-drawer-toggle="#kt_header_menu_mobile_toggle" data-kt-swapper="true" data-kt-swapper-mode="prepend" data-kt-swapper-parent="{default: '#kt_body', lg: '#kt_header_nav'}">
				<!--begin::Menu-->
				<div class="menu menu-lg-rounded menu-column menu-lg-row menu-state-bg menu-title-gray-700 menu-state-title-primary menu-state-icon-primary menu-state-bullet-primary menu-arrow-gray-400 fw-bold my-5 my-lg-0 align-items-stretch" id="#kt_header_menu" data-kt-menu="true">
					<div class="menu-item">
						<a class="menu-link py-3" asp-controller="Home" asp-action="Index" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
							<span class="menu-icon">
								<i class="bi bi-house-door fs-3"></i>
							</span>
							<span class="menu-title">Dashboard</span>
						</a>
					</div>
					<div class="menu-item">
						<a class="menu-link py-3" asp-controller="Personnel" asp-action="Index" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
							<span class="menu-icon">
								<i class="bi bi-ui-checks fs-3"></i>
							</span>
							<span class="menu-title">Personnel</span>
						</a>
					</div>
					<div class="menu-item">
						<a class="menu-link py-3" asp-controller="Team" asp-action="Index" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
							<span class="menu-link py-3">
								<span class="menu-icon">
									<i class="bi bi-clipboard-check fs-3"></i>
								</span>
								<span class="menu-title">Team</span>
							</span>
						</a>
					</div>
					<div class="menu-item">
						<a class="menu-link py-3" asp-controller="Shift" asp-action="Index" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
							<span class="menu-link py-3">
								<span class="menu-icon">
									<i class="bi bi-files fs-3"></i>
								</span>
								<span class="menu-title">Shift</span>
							</span>
						</a>
					</div>
					@*<div data-kt-menu-trigger="click" data-kt-menu-placement="bottom-start" class="menu-item menu-lg-down-accordion me-lg-1">
						<span class="menu-link py-3">
							<span class=" menu-icon">
								<i class="bi bi-lock fs-3"></i>
							</span>
							<span class="menu-title">Log İşlemleri</span>
							<span class="menu-arrow d-lg-none"></span>
						</span>
						<div class="menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-lg-225px">
							<div class="menu-item">
								<a class="menu-link py-3" asp-controller="" asp-action="Index" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-dismiss="click" data-bs-placement="right">
									<span class="menu-icon">
										<i class="bi bi-list fs-3"></i>
									</span>
									<span class="menu-title">Kullanıcı Giriş Logları</span>
								</a>
							</div>
						</div>
					</div>*@
				</div>
				<!--end::Menu-->
			</div>
			<!--end::Menu wrapper-->
		</div>
		<!--end::Navbar-->
		<!--begin::Topbar-->
		<div class="d-flex align-items-stretch flex-shrink-0">
			<!--begin::Toolbar wrapper-->
			<div class="d-flex align-items-stretch flex-shrink-0">
				<!--begin::User-->
				<div class="d-flex align-items-center ms-1 ms-lg-3" id="kt_header_user_menu_toggle">
					<!--begin::Menu wrapper-->
					<div class="cursor-pointer symbol symbol-30px symbol-md-40px" data-kt-menu-trigger="click" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end" data-kt-menu-flip="bottom">
						<img src="/Metronic/assets/media/avatars/blank.png" alt="metronic" />
					</div>
					<!--begin::Menu-->
					<div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-primary fw-bold py-4 fs-6 w-275px" data-kt-menu="true">
						<!--begin::Menu item-->
						<div class="menu-item px-3">
							<div class="menu-content d-flex align-items-center px-3">

								<!--begin::Username-->
								<div class="d-flex flex-column">
									<div class="fw-bolder d-flex align-items-center fs-5">
										AdSoyad
									</div>
									<a href="#" class="fw-bold text-muted text-hover-primary fs-7">Email</a>
								</div>
								<!--end::Username-->
							</div>
						</div>
						<!--end::Menu item-->
						<!--begin::Menu separator-->
						<div class="separator my-2"></div>
						<!--end::Menu separator-->
						<!--begin::Menu item-->
						<div class="menu-item px-5">
							<a asp-controller="" asp-action="LogOut" asp-route-returnUrl="/Home" class="menu-link px-5">Çıkış Yap</a>
						</div>
						<!--end::Menu item-->
					</div>
					<!--end::Menu-->
					<!--end::Menu wrapper-->
				</div>
				<!--end::User -->
				<!--begin::Heaeder menu toggle-->
				<div class="d-flex align-items-center d-lg-none ms-2" title="Show header menu">
					<div class="btn btn-icon btn-active-color-primary w-30px h-30px w-md-40px h-md-40px" id="kt_header_menu_mobile_toggle">
						<!--begin::Svg Icon | path: icons/duotone/Text/Toggle-Right.svg-->
						<span class="svg-icon svg-icon-1">
							<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
								<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
									<rect x="0" y="0" width="24" height="24" />
									<path fill-rule="evenodd" clip-rule="evenodd" d="M22 11.5C22 12.3284 21.3284 13 20.5 13H3.5C2.6716 13 2 12.3284 2 11.5C2 10.6716 2.6716 10 3.5 10H20.5C21.3284 10 22 10.6716 22 11.5Z" fill="black" />
									<path opacity="0.5" fill-rule="evenodd" clip-rule="evenodd" d="M14.5 20C15.3284 20 16 19.3284 16 18.5C16 17.6716 15.3284 17 14.5 17H3.5C2.6716 17 2 17.6716 2 18.5C2 19.3284 2.6716 20 3.5 20H14.5ZM8.5 6C9.3284 6 10 5.32843 10 4.5C10 3.67157 9.3284 3 8.5 3H3.5C2.6716 3 2 3.67157 2 4.5C2 5.32843 2.6716 6 3.5 6H8.5Z" fill="black" />
								</g>
							</svg>
						</span>
						<!--end::Svg Icon-->
					</div>
				</div>
				<!--end::Heaeder menu toggle-->
			</div>
			<!--end::Toolbar wrapper-->
		</div>
		<!--end::Topbar-->
	</div>
	<!--end::Wrapper-->
</div>